version: "3.7"
services:
  brahma:
    container_name: brahma-app
    restart: always
    image: brahma
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_ADDR=brahma-mongo
      - MONGO_PORT=27017
      - PORT=80
    ports:
      - "80:80"
  mongo:
    container_name: brahma-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
    external: true
  mongo_config:
    external: true
